### PR TITLE
General updates to alez

### PR DESCRIPTION
**Pull request by vlmarek**
Hi,

I wanted to install arch linux onto zfs and found Alez. Alez worked great for me at the end, but I had few problems. I'm trying to improve everything I had problem with. Hopefully you'll find the changes helpful too. This is first time I have been installing arch so hopefully I have picked up the system correctly.

Thank you
__ 
  Vlad

### CODE REVIEW

**Comment by danboid** [comment]
Thanks Vlad!

It all looks good to me. I see your point about the Stable / LTS kernel naming scheme but that is how the Arch docs, wiki and packaging refer to them so I'm going to revert that but change it to Stable (standard kernel) so it should be clear to everyone what is being installed.

**Comment by danboid** [comment]
One of your commits has broken dialog during GRUB installation: --menu is expecting 5 tokens (parameters) and its only getting 4.

**Comment by danboid** [comment]
One of your commits had broken get_disks(). I have restored the old get_disks() and now GRUB installation is working again.

The bug where partition creation fails if the user doesn't view partitions first remains though.

**Comment by danboid** [comment]
Sorry, the bug occurs when not choosing to view partitions before choosing a partition to create a pool on, not when creating partitions. I'll have a look at it soon.

**Comment by vlmarek** [comment]
Hi,

thanks for looking onto the changes. And sorry if I caused any trouble. I have noticed that travis is failing too, but I will wait for you to decide what to do with the changes before going further.

__ 
  Vlad

**Comment by danboid** [comment]
No problem Vlad! Thanks for testing ALEZ and submitting patches but please try to test your changes before making a pull request in future please!

My latest commit fixes pool creation when the user chooses not to view the partitions beforehand.

**Comment by danboid** [comment]
When I say test your changes, I'd request that you successfully complete a single disk BIOS (or UEFI) GRUB ALEZ installation using your updated script in a VM and check that the installed VM boots after installation.

Thanks Vlad!

**Pull request merged**
