### PR TITLE
Shellcheck Testing

### PR DESCRIPTION
**Pull request by johnramsden**
## Shellcheck Testing

It might be nice to have a little bit of automated testing, even if it's just validating our code quality is up to par. This PR fixes any current issues we have that shellcheck fails, and that adds a test to Travis CI. 

It also only considers the shellcheck test important when determining whether or not a build passed, and will not report a failure if an ISO fails to build. I think this makes sense since we might otherwise have recurring failures if the archzfs are out of sync from the current Linux release. 

So if the shellheck passes, it will report a success whether or not the ISO was able to build successfully. If the ISO does successfully build it will release it.

I have split the PR up fixing individual shellcheck issues in each commit, if preferred I can squash them into a single commit.

**PR Tests**
* [x] Ran the TravisCI build, and it is working as detailed above
* [x] Ran through an install with the changes to the script

### CODE REVIEW

**Comment by danboid** [comment]
All sounds good to me but what's the "Don't fail if ISO build fails" commit for? I'm not concerned if every other commit fails to bulld a new ISO because the repos are out of sync and I'd prefer to not have the releases page too heavily clogged so I'm happy with builds failing (due to out-of-sync repos) now and again. I don't want to have new releases created for every commit without an ISO.

I can confirm that the travis/docker ISO build scripts work as I have installed from the latest, travis built release. As I said in a recent mail, I'd like to adjust the iso build script to rename the iso to archlinux-alez-$DATE and use that for the github release title too. It would be cool if we can print the Linux kernel version and ZoL versions in the gh release description too.

**Comment by johnramsden** [comment]
The idea would be a release would not occur at all if the ISO build fails. The build would still run shellcheck though, and pass/fail would be determined by that. It's easy to change though if you prefer an explicit ERROR on Travis on ISO failure.

**Comment by danboid** [comment]
Oh OK, I'd be happy with that as it is then.

**Comment by johnramsden** [comment]
Ran through some tests and made any necessary adjustments. Tested on UEFI, and BIOS.

**Comment by danboid** [comment]
Thanks John!

**Pull request merged**
